myhomework24/myhomework24/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include("shop.urls")),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include("debug_toolbar.urls"))
    ]

myhomework24/shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"
urlpatterns = [
    path('', views.shop_list, name='shop_list'),
    path('<int:pk>/', views.shop_detail, name='shop_detail'),
    path('new/', views.shop_new, name='shop_new'),
    path('<int:pk>/edit/', views.shop_edit, name='shop_edit'),
    path('<int:pk>/delete/', views.shop_delete, name='shop_delete'),
    path('<int:shop_pk>/review/new/', views.review_new, name='review_new'),
    path('<int:shop_pk>/review/<int:pk>/edit/', views.review_edit, name='review_edit'),
    path('<int:shop_pk>/review/<int:pk>/delete/', views.review_delete, name='review_delete'),
]

myhomework24/shop/models.py
from django.db import models


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(TimestampedModel):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["-id"]


class Shop(TimestampedModel):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    content = models.TextField()
    tag_set = models.ManyToManyField("Tag", blank=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ["-id"]


class Review(TimestampedModel):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self):
        return self.message

    class Meta:
        ordering = ['-id']


class Tag(TimestampedModel):
    name = models.CharField(max_length=200, db_index=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["name"]

myhomework24/shop/forms.py
from django import forms
from shop.models import Shop, Review


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = "__all__"


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"

myhomework24/shop/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from shop.forms import ShopForm, ReviewForm
from shop.models import Shop, Review

shop_list = ListView.as_view(
    model=Shop,
)

shop_detail = DetailView.as_view(
    model=Shop,
)


class ShopCreateView(CreateView):
    model = Shop
    form_class = ShopForm

    def get_success_url(self):
        shop_pk = self.object.pk
        return reverse("shop:shop_detail", args=[shop_pk])  # 문자열


shop_new = ShopCreateView.as_view()


class ShopUpdateView(UpdateView):
    model = Shop
    form_class = ShopForm

    def get_success_url(self):
        shop_pk = self.object.pk
        return reverse("shop:shop_detail", args=[shop_pk])


shop_edit = ShopUpdateView.as_view()

shop_delete = DeleteView.as_view(
    model=Shop,
    success_url=reverse_lazy("shop:shop_list"),
)


class ReviewCreateView(CreateView):
    model = Review
    form_class = ReviewForm

    def get_success_url(self):
        shop_pk = self.object.shop.pk
        return reverse("shop:shop_detail", args=[shop_pk])  # 문자열


review_new = ReviewCreateView.as_view()


class ReviewUpdateView(UpdateView):
    model = Review
    form_class = ReviewForm

    def get_success_url(self):
        shop_pk = self.object.shop.pk
        return reverse("shop:shop_detail", args=[shop_pk])


review_edit = ReviewUpdateView.as_view()


class ReviewDeleteView(DeleteView):
    model = Review

    def get_success_url(self):
        shop_pk = self.object.shop.pk
        return reverse("shop:shop_detail", args=[shop_pk])


review_delete = ReviewDeleteView.as_view()

myhomework24/shop/templates/shop/layout.html
{% load bootstrap5 %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>이준수 컴퍼니</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
<div class="container">
    {% bootstrap_messages %}
    <h1>상점</h1>

    {% block content %}
    {% endblock %}

    <hr>
    &copy; 준수 마켓
</div>


</body>
</html>

myhomework24/shop/templates/shop/review_confirm_delete.html
{% extends "shop/layout.html" %}

{% block content %}
    <h2>Review 삭제를 확인</h2>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제하겠습니다.">
    </form>

    <a href="{% url "shop:shop_detail" object.pk %}">
        Detail 로 돌아가기
    </a>

{% endblock %}

myhomework24/shop/templates/shop/review_form.html
{% extends "shop/layout.html" %}

{% block content %}

    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit"/>
    </form>

{% endblock %}

myhomework24/shop/templates/shop/shop_confirm_delete.html
{% extends "shop/layout.html" %}

{% block content %}
    <h2>Shop 삭제를 확인</h2>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제하겠습니다.">
    </form>

    <a href="{% url "shop:shop_detail" shop.pk %}">
        Detail로 돌아가기
    </a>

{% endblock %}

myhomework24/shop/templates/shop/shop_detail.html
{% extends "shop/layout.html" %}

{% block content %}
    <h2>{{ shop.title }}</h2>

    <p>
        {% for tag in shop.tag_set.all %}
            {{ tag.name }}
        {% endfor %}
    </p>

    {{ shop.content|linebreaks }}

    <ul>
        {% for review in object.review_set.all %}
            <li>
                {{ review.message }}
                at
                <span title="{{ review.created_at }}">
                    {{ review.created_at|timesince }} 전
                </span>
                <a href="{% url "shop:review_edit" shop.pk review.pk %}">수정하기</a>
                <a href="{% url "shop:review_delete" shop.pk review.pk %}">삭제하기</a>
            </li>
        {% endfor %}
    </ul>
    <hr/>
    <a href="{% url "shop:shop_list" %}">
        포스팅 목록
    </a>

    <a href="{% url "shop:shop_edit" shop.pk %}">
        포스팅 수정
    </a>

    <a href="{% url "shop:shop_delete" shop.pk %}">
        포스팅 삭제
    </a>

    <a href="{% url "shop:review_new" shop.pk %}">
        리뷰 쓰기
    </a>

{% endblock %}

myhomework24/shop/templates/shop/shop_form.html
{% extends "shop/layout.html" %}

{% block content %}
    <h2>Shop Form</h2>

    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit"/>
    </form>


    <hr/>
    {% if shop %}
        <a href="{% url "shop:shop_detail" shop.pk %}">
            조회화면으로
        </a>
    {% endif %}
{% endblock %}

myhomework24/shop/templates/shop/shop_list.html
{% extends "shop/layout.html" %}

{% block content %}
    <h2>Shop List</h2>
    <table>
        <thead>
        {% for shop in shop_list %}
            <tr>
                <td>
                    <a href="{% url "shop:shop_detail" shop.pk %}">
                        {{ shop.title }}
                    </a>
                </td>
            </tr>
        {% endfor %}
        </thead>
    </table>

    <hr/>

    <a href="{% url "shop:shop_new" %}">
        포스팅 쓰기
    </a>

{% endblock %}