mypractice01/comic/urls.py
from django.urls import path

from comic import views

app_name = 'comic'

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("new/", views.post_new, name="post_new"),
    path("<int:pk>/edit/", views.post_edit, name="post_edit"),
    path("<int:post_pk>/review/new", views.review_new, name="review_new"),
    path("<int:post_pk>/review/<int:pk>/edit", views.review_edit, name="review_edit"),
]

mypractice01/mypractice01/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

def root(request):
    return redirect("comc:post_list")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comic/', include("comic.urls")),
    path('', root, name="root"),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

mypractice01/comic/models.py
from django.db import models


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(TimestampedModel):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["-id"]


class Post(TimestampedModel):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    content = models.CharField(max_length=200)
    tag_set = models.ManyToManyField("Tag", blank=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ["-id"]


class Review(TimestampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    message = models.TextField()

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["-id"]


class Tag(TimestampedModel):
    name = models.CharField(max_length=200, db_index=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["name"]

mypractice01/comic/forms.py
from django import forms

from comic.models import Post, Tag, Review


class PostForm(forms.ModelForm):
    tags = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:  # 수정 시
            tag_qs = self.instance.tag_set.all()
            tags = ", ".join([tag.name for tag in tag_qs])
            self.fields["tags"].initial = tags

    def save(self):
        saved_post = super().save()

        tag_list = []
        tags = self.cleaned_data.get("tags", "")
        for word in tags.split(","):
            tag_name = word.strip()
            tag, __ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)

        saved_post.tag_set.clear()
        saved_post.tag_set.add(*tag_list)
        return saved_post

    class Meta:
        model = Post
        fields = ["category",
                  "title",
                  "content",
                  ]


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["name",  "message"]

mypractice01/comic/views.py
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from comic.forms import PostForm, ReviewForm
from comic.models import Post, Category, Review


def post_list(request: HttpRequest) -> HttpResponse:
    qs = Post.objects.all()
    category_qs = Category.objects.all()

    category_id: str = request.GET.get("category_id", "")
    if category_id:
        qs = qs.filter(category__pk=category_id)

    query = request.GET.get("query", "")
    if query:
        qs = qs.filter(name__icontains=query)

    return render(request, "comic/post_list.html", {
        "post_list": qs,
        "category_list": category_qs
    })


def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    review_list = post.review_set.all()
    return render(request, "comic/post_detail.html", {
        "post": post,
        "review_list": review_list,
    })


def post_new(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            saved_post = form.save()

            return redirect("comic:post_detail", saved_post.pk)
    else:
        form = PostForm()

    return render(request, "comic/post_form.html", {
        "form": form,
    })


def post_edit(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            saved_post = form.save()
            # shop_detail 뷰를 구현했다면 !!!
            return redirect("comic:post_detail", saved_post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, "comic/post_form.html", {
        "form": form,
    })


def review_new(request, post_pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.post = post
            review.save()
            return redirect("comic:post_detail", post_pk)
    else:
        form = ReviewForm()
    return render(request, "comic/review_form.html", {
        "form": form,
    })


def root(request):
    return redirect("comic:post_list")


def review_edit(request: HttpRequest, post_pk: int, pk: int) -> HttpResponse:
    review = get_object_or_404(Review, pk=pk)
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            form.save()
            messages.success(request, "성공적으로 저장했습니다.")
            return redirect("comic:post_detail", post_pk)
    else:
        form = ReviewForm(instance=review)

    return render(request, "comic/review_form.html", {
        "form": form,
    })

mypractice01/comic/templates/comic/layout.html
{% load bootstrap5 %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>노래</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<div class="container">
    {% bootstrap_messages %}
    <h1>노래</h1>

    {% block content %}

    {% endblock %}

    <hr>
    &copy; 2021. 준수박스
</div>


</body>
</html>

mypractice01/comic/templates/comic/post_detail.html
{% extends "comic/layout.html" %}

{% block content %}
    <h2>{{ post.title }}</h2>
    <p>
        {% for tag in post.tag_set.all %}
            <span class="badge" style="background-color: aqua;">
            {{ tag.name }}
        </span>
        {% endfor %}
    </p>
    {{ post.content }}
    <hr>
    {{ post.created_at|timesince }}

    <h3>댓글</h3>

    <a href="{% url "comic:review_new"  post.pk %}">댓글 쓰기</a>

    <ul>
        {% for review in review_list %}
            <li>
                {{ review.message }}
                by {{ review.name }}
                <span title="{{ review.created_at }}">
                    {{ review.created_at|timesince }} 전
                </span>

                <a href="{% url "comic:review_edit"  post.pk review.pk %}">Edit</a>
            </li>
        {% endfor %}
    </ul>


    <hr>

    <a href="{% url "comic:post_list" %}">
        목록으로
    </a>

    <a href="{% url "comic:post_edit" post.pk %}">
        수정하기
    </a>


{% endblock %}

mypractice01/comic/templates/comic/post_form.html
{% extends "comic/layout.html" %}

{% block content %}

    <h2>Shop Form</h2>

    <form action="" method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input  type="submit" value="저장하기" />
    </form>

{% endblock %}

mypractice01/comic/templates/comic/post_list.html
{% extends "comic/layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            <div class="d-grid mb-3">
                <a href="{% url "comic:post_new" %}" class="btn btn-primary">새 포스팅 쓰기</a>
            </div>
            <form action="" method="get" class="mb-3">
                <input type="text" name="query" placeholder="검색어를 입력해주세요." value=""{{ reques.GET.query }} />
                <input type="submit" value="검색">
            </form>
            <ul>
                {% for post in post_list %}
                    <li>
                        <a href="{% url "comic:post_detail" post.pk %}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-sm-4">

            <ul>
                <li>
                    <a href="?category_id=">전체</a>
                </li>
                {% for category in category_list %}
                    <li>
                        <a href="?category_id={{ category.pk }}">
                            {{ category.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

mypractice01/comic/templates/comic/review_form.html
{% extends "comic/layout.html" %}
{% load bootstrap5 %}

{% block content %}

    <form action="" method="post" enctype="multipart/form-data">
         <h2>Review Form</h2>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit"
                    value="저장하기"
                    class="btm btn-primary" />
    </form>


{% endblock %}