mydjango23/accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"

urlpatterns = [
    path("profile.png", views.profile_image, name="profile_image"),
    path("login/", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout"),
]

mydjango23/blog/urls.py
from django.urls import path

from blog.views import fbv as views       # 함수 기반
# from blog.views import cbv as views         # 클래스 기반


app_name = "blog"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),
    path("subscriber/new/", views.subscriber_new, name="subscriber_new"),
]

mydjango23/mydjango23/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    # FIXME: 아래의 url 설정은 blog 기능 구현 후에 pattern_name으로 변경 예정
    path('', RedirectView.as_view(url='/blog/'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mydjango23/blog/models.py
import tablib
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(TimestampedModel):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Post(TimestampedModel):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    content = models.TextField()
    photo = models.ImageField(upload_to="blog/post/%Y/%m/%d")
    tag_set = models.ManyToManyField('Tag', blank=True)
    status = models.CharField(
        max_length=1,
        # FIXME: 장고 3에서 추가된 TextChoices 기능을 활용
        choices=[
            ('D', '초안'),  # Draft // DB저장값, Label
            ('P', '공개'),  # Published
        ],
        db_index=True,
        default='D',
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.pk])

    @classmethod
    def get_tabular_data(cls, queryset, format="xlsx") -> bytes:
        dataset = tablib.Dataset()
        dataset.headers = ["id", "title", "created_at", "updated_at"]
        for post in queryset:
            dataset.append([
                post.id,
                post.title,
                post.created_at.strftime("%Y-%m-%d %H:%M:%S"),
                post.updated_at.strftime("%Y-%m-%d %H:%M:%S"),
            ])

        return dataset.export(format)

    class Meta:
        ordering = ['-id']


class Comment(TimestampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self):
        return self.message

    class Meta:
        ordering = ['-id']


class Tag(TimestampedModel):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Subscriber(TimestampedModel):
    phone = models.CharField(
        max_length=15,
        validators=[
            RegexValidator(
                r"^\d{3,4}-?\d{3,4}-?\d{4}$"
            ),
        ]
    )

mydjango23/blog/forms.py
import re

from django import forms
from blog.models import Post, Tag, Subscriber


class PostForm(forms.ModelForm):
    tags = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance.pk:
            tag_qs = self.instance.tag_set.all()
            initial = ", ".join([tag.name for tag in tag_qs])
            self.fields["tags"].initial = initial

    # DB 로의 저장
    # def save(self, commit=True):
    #     saved_post = super().save(commit)
    # def save(self, commit=False):
    # 아래 함수가 호출되기 전에 instance.save()가 호출 되었음을 보장받는다.
    def _save_m2m(self):
        super()._save_m2m()

        tag_list = []
        tags = self.cleaned_data.get("tags", "")
        for word in tags.split(","):
            tag_name = word.strip()
            tag, __ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)

        self.instance.tag_set.clear()
        self.instance.tag_set.add(*tag_list)

    def clean_content(self):
        content = self.cleaned_data.get("content")
        if content:
            # script 태그를 제거
            content = re.sub(r'<script.*?>.*?</script>', '', content, flags=re.I | re.S)
        return content

    class Meta:
        model = Post
        fields = [
            "category",
            "title",
            "content",
            "photo",
            "status",
        ]


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = "__all__"

    # Form 만의 유효성 검사 방법 + 데이터 변환 기능 제공
    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        if phone:
            if not phone.startswith("010"):
                raise forms.ValidationError("010으로 시작하도록 입력해주세요.")
        return phone.replace("-", "")

mydjango23/blog/views/cbv.py
# Class Based View(CBV)
#   - 뷰 함수를 만들어주는 클래스
from django.shortcuts import resolve_url
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from blog.forms import PostForm
from blog.models import Post
post_list = ListView.as_view(
    model=Post,
)
post_detail = DetailView.as_view(
    model=Post,
)


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    # success_url = reverse_lazy("blog:post_list")

    def get_success_url(self):
        # self.object  # 저장된 모델 인스턴스
        post_pk = self.object.pk
        return reverse("blog:post_detail", args=[post_pk])  # 문자열
        # return resolve_url("blog:post_detail", post_pk)  # 문자열
        # return redirect   ("blog:post_detail", post_pk)  # HttpResponse
        #           {% url "blog:post_detail" post_pk %}  # 문자열


post_new = PostCreateView.as_view()


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm

    def get_success_url(self):
        post_pk = self.object.pk
        return reverse("blog:post_detail", args=[post_pk])


post_edit = PostUpdateView.as_view(
    # model=Post,
    # form_class=PostForm,
    # # TODO: 가변적으로 URL을 지정할 수 없다.
    # # TODO: URL Reverse가 미적용
    # # success_url="/blog/",
    # # success_url="blog:post_list",  # URL Reverse 미지원
    # # success_url=reverse("blog:post_list"),
    # success_url=reverse_lazy("blog:post_list"),
)


post_delete = DeleteView.as_view(
    model=Post,
    success_url=reverse_lazy("blog:post_list"),
)

mydjango23/blog/views/fbv.py
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView

from blog.forms import PostForm, SubscriberForm
from blog.models import Post, Subscriber


def post_list(request: HttpRequest) -> HttpResponse:
    # print(request.GET)
    # print(request.GET.get("name"))  # dict 의 방식
    # print(request.GET.get["name"])      # dict 의 방식
    # print(request.GET.getlist("name"))  # MultiValueDict에서 지원

    post_qs = Post.objects.all()

    format = request.GET.get("format", "")

    if format == "xlsx":
        tabular_data = Post.get_tabular_data(post_qs, format="xlsx")
        return HttpResponse(tabular_data, content_type="application/vnd.ms-excel")
    elif format == "json":
        tabular_data = Post.get_tabular_data(post_qs, format="json")
        return HttpResponse(tabular_data, content_type="application/json")

    return render(request, 'blog/post_list.html', {
        'post_list': post_qs,
    })


def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    return render(request, "blog/post_detail.html", {
        "post": post,
    })


def post_new(request: HttpRequest) -> HttpResponse:
    # request.method  # "GET", "POST"

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            saved_post = form.save()
            messages.success(request, "새로운 포스팅을 저장했습니다.")
            return redirect("blog:post_detail", saved_post.pk)
    else:
        form = PostForm()

    return render(request, "blog/post_form.html", {
        "form": form,
    })


def post_edit(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            saved_post = form.save()
            messages.success(request, f"#{pk} 포스팅을 저장했습니다.")
            return redirect("blog:post_detail", saved_post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'blog/post_form.html', {
        "form": form,
        "post": post,
    })


def post_delete(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    # GET 요청 : 정말 삭제를 할 것인지, 한 번 더 물어본다.
    # POST 요청 : 삭제를 하고, 다른 주소로 이동을 시킨다.

    if request.method == "POST":
        post.delete()
        messages.success(request, f"#{pk} 포스팅을 삭제했습니다.")
        return redirect("blog:post_list")

    return render(
        request,
        "blog/post_confirm_delete.html",
        {
            "post": post
        }
    )

    return render(request, "blog/post_confirm_delete.html", {
        "post": post,
    })


subscriber_new = CreateView.as_view(
    model=Subscriber,
    form_class=SubscriberForm,
)

mydjango23/blog/templates/blog/layout.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>웹툰</title>
</head>
<body>
<h1>웹툰</h1>


<ul>
    {% if not user.is_authenticated %}
        <li><a href="{% url "accounts:login" %}">로그인</a></li>
        <li><a href="{% url "accounts:signup" %}">회원가입</a></li>
    {% else %}
        <li><a href="{% url "accounts:profile" %}">
            {{ user.username }}'s
            프로필
        </a></li>

        <li><a href="{% url "accounts:logout" %}">로그아웃</a></li>
    {% endif %}
</ul>


{% block content %}
{% endblock %}

<hr>
&copy; 준스 툰즈

</body>
</html>

mydjango23/blog/templates/blog/post_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>Post 삭제를 확인</h2>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제하겠습니다.">
    </form>

    <a href="{% url "blog:post_detail" post.pk %}">
        Detail로 돌아가기
    </a>

{% endblock %}

mydjango23/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>{{ post.title }}</h2>

    <p>
        {% for tag in post.tag_set.all %}
            {{ tag.name }}
        {% endfor %}
    </p>

    <img src="{{ post.photo.url }}" alt="{{ post.title }}">

    {{ post.content|linebreaks }}

    <hr/>
    <a href="{% url "blog:post_list"  %}">
        포스팅 목록
    </a>
    <a href="{% url "blog:post_edit" post.pk %}">
        포스팅 수정
    </a>

    <a href="{% url "blog:post_delete" post.pk %}">
        포스팅 삭제
    </a>
{% endblock %}

mydjango23/blog/templates/blog/post_form.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>Post Form</h2>

    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit"/>
    </form>

    <hr/>
    {% if post %}
        <a href="{% url "blog:post_detail" post.pk %}">
            조회화면으로(취소)
        </a>
    {% endif %}
{% endblock %}

mydjango23/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>Post List</h2>

    <table>
        <thead>
            {% for post in post_list %}
                <tr>
                    <td>
                        <a href="{% url "blog:post_detail" post.pk %}">
                            {{ post.title }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </thead>
    </table>

    <hr />

    <a href="{% url "blog:post_new" %}">
        포스팅 쓰기
    </a>
{% endblock %}

mydjango23/blog/templates/blog/subscriber_form.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>Subscriber Form</h2>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>
{% endblock %}